PINECONE_API = 'd002be83-9dae-4a1a-87fb-7fd1c9efd7df'
PINECONE_ENV = 'us-west1-gcp'
PINECONE_INDEX = 'typing-agent-main'
PINECONE_ENV_ADA = 'us-west1-gcp'
PINECONE_INDEX_ADA = 'ta-ada-002'
OPENAI_KEY = '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'